### ISSUE TITLE
Text field requires manual deletion of hint text

### ISSUE THREAD

**Issue by Shashwat-111** [pierremrtn/firestore_modeler#5]
For adding text in any text field, one has to manually delete the text, which gets irritating. 
It should disappear automatically when typing, using Flutter's default hintText behavior.
![image](https://github.com/user-attachments/assets/cce60f33-faf9-4399-ab9e-9bc9f8060ebe)

**Comment by pierremrtn** [comment]
Good point, I'll fix that tomorrow

**Comment by pierremrtn** [comment]
Fixed
